### ISSUE TITLE
Slow law list display

### ISSUE THREAD

**Issue by heldergg** [jorgecarleitao/public-contracts#20]
When I try to access a given page that I haven't accessed before the page generation is extremely slow (sometimes we even get a 504 error). For example:

    http://publicos.pt/lei?page=2500
    (Change the page number)
  
I think this can be fixed simply indexing the law table against 'dre_doc_id' or some such.

**Comment by jorgecarleitao** [comment]
I'm closing this as we are now using postgres, and the issue doesn't not seem to exist anymore.
