### ISSUE TITLE
Can't no longer run contracts.tests

### ISSUE THREAD

**Issue by nmota** [jorgecarleitao/public-contracts#57]
After latest updates, running manage.py test contracts.tests gives following error:    

`from django.db.models import Value, F, TextField
ImportError: cannot import name 'Value'`

Am I missing something? 
Also in order to install psycopg2 had to install libpq-dev python-dev packages

**Comment by jorgecarleitao** [comment]
We are requiring Django 1.8, released yesterday or so, since I upgraded django-sphinxql to allow indexing data from Foreign fields.

For psycopg2, I'm sorry, I tried on travis and Mac os and it was working fine. Is there anything we can add to readme?

**Comment by nmota** [comment]
It seems that this is more of problem of my system configuration and lack of general knowledge than anything else. Thanks for the help.

**Comment by jorgecarleitao** [comment]
@nmota, you need any help (for your system conf. or general knowledge), please let me know. You  can reach me by email if you don't think it shouldn't be discussed here.

**Comment by jorgecarleitao** [comment]
Btw, ebb1035135d11ac630cd5ccd5e96da6196526b02 updated travis' configuration to test the contracts app. There you can see what you should install to run the contracts tests. I'm closing this issue, but feel free to open if you believe something can be further improved.
