### ISSUE TITLE
AttributeError: 'QuerySet' object has no attribute 'search' on searching on Type

### ISSUE THREAD

**Issue by jorgecarleitao** [jorgecarleitao/public-contracts#61]
```
Internal Server Error: /tipo/4/decreto-lei
Traceback (most recent call last):
  File ".../lib/python3.3/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File ".../public-contracts/law/views.py", line 104, in type_view
    context = build_laws_list_context(context, request.GET)
  File ".../public-contracts/law/views.py", line 47, in build_laws_list_context
    context['laws'] = context['laws'].search(GET[key])
AttributeError: 'QuerySet' object has no attribute 'search'
```

**Comment by nmota** [comment]
I've been looking into this.
It seems that changing the context from:

`type.document_set.order_by("-date").prefetch_related("type")`

to:

`indexes.DocumentIndex.objects.filter(type__name=type.name).order_by("-date").prefetch_related("type")`

would fix the issue.

**Comment by jorgecarleitao** [comment]
Should be close to that. With that the search will be done over all documents, and only then Django filters the ones of a given `type__name`. We want to have the search itself restricted to a given `type__name`. In principle that would be done `search("@name %s" % type.name)`, but that activates `search_mode`, which we don't want if the user didn't made any search.

See if this makes sense: add the search call above to restrict the search and activate the search mode, but in the `build_laws_list_context`, add an `else`:

```
key = 'search'
if key in GET and GET[key]:
    ....
else:
    context['laws'].search_mode = False
```

to enforce that the search is not to be used if there was no `search` request in GET.
