### ISSUE TITLE
Use pt_law_parser

### ISSUE THREAD

**Issue by jorgecarleitao** [jorgecarleitao/public-contracts#65]
I've been working on a parser of the portuguese law that I outsourced to [pt_law_parser](https://github.com/publicos-pt/pt_law_parser). I believe it is ready to be used by publicos.pt.

The package defines an interface to parse and interpret texts obtained from [pt_law_downloader](https://github.com/publicos-pt/pt_law_downloader) and it already reproduces the results we obtain with our current code. It is much more general than the one we have now: it contains a tokenizer, a parser and a analyser to convert pure text into tokens, references, section titles, law references, etc.

It fixes also issues #58 and #62.

The main limitation is that, as our parser, it takes time to parse the text. Since the document only needs to be parsed once for a given version of the parser, I propose we add a new field, `Document.composed_text`, that stores the html text, so we don't need to run the parser for every request.

**Comment by nmota** [comment]
That sounds great!
While you are at it, wouldn't be possible with the new parser to distinguish references that change the documents or revoke them?

**Comment by jorgecarleitao** [comment]
:) Yap, that is the aim: allow to construct "versions" of each document based on modifications done by other documents (in which revoke is a type of modification).

Technically this is difficult because... well, it is natural language processing. The hope here is that law is a "semi"-natural language since it contains a "semi"-rigid structure.

My plan is the following:
1. be able to identify *which* elements define the document structure, such as artigos and alíneas, to create a generic structure of the document. 
2. be able to identify *when* the text refers to these elements. 
3. be able to identify *what* the references do on citing (i.e. just citing, or changing?).

pt_law_parser will be responsible of 1. and part of 2 and 3. Step 2. requires cross-references to other documents (which require a DB of documents) and step 3. requires building a db of references.

Ideally, we want to be able to build statements such as `Art. 1 of Decreto-Lei 2/2010 of 2/2/2010` `changes` `Art. 2 of Decreto-Lei 2/2002 of 10/2/2002` `from ...` `to ...`, pretty much like git does with code.
