### ISSUE TITLE
Entities rss feed is broken in contracts app

### ISSUE THREAD

**Issue by nmota** [jorgecarleitao/public-contracts#66]
It seems that there is no url pattern pointing to a view.

**Comment by jorgecarleitao** [comment]
We have to decide whether we keep the RSS and fix it, or just remove it. 

Unfortunately we have no way to measure the usage of RSS as no analytics is measured.

**Comment by nmota** [comment]
Since it is broken and nobody complained yet....maybe we could just remove it. The usefulness of the rss feed in this case seems rather limited to me.

**Comment by jorgecarleitao** [comment]
I agree with you.

**Comment by jorgecarleitao** [comment]
Fixed in 63dd61c39ab5e5e01a0e8308e272733fcf20d820.
